version: 0.2

env:
 variables:
  PACKAGE: "github.com/jasonGeng88/beego-demo"
phases:
 install:
  commands:
   # AWS Codebuild Go images use /go for the $GOPATH so let's copy our 
   # application source code into that directory structure.
   - mkdir -p "/go/src/$(dirname ${PACKAGE})"
   - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}" 
   - env
   - echo Nothing to do in the install phase...
 pre_build:
  commands:
   # Make sure we're in the project directory within our GOPATH
   - cd "/go/src/${PACKAGE}"
   - go test .
 build:
  commands:
   - go build
 post_build:
  commands:
   - echo Build completed on `date`
artifacts:
 files:
  - run.sh
  - beego-demo
  - appspec.yml
  - conf/**/*
  - static/**/*
  - views/**/*
